FROM php:8.2-rc-fpm-alpine3.18

# Args to create user
ARG user=celso
ARG uid=1000

# Update alpine image and install packeges
RUN apk --update --no-cache add curl \
    zip \
    unzip \
    vim \
    libpng-dev \
    libxml2-dev \
    libzip \
    libzip-dev \
    oniguruma-dev \
    linux-headers \
    git

# Install packages to run PHP/laravel and our app
RUN apk --update --no-cache add php82-bcmath \
    php82-bz2 \
    php82-calendar \
    php82-exif \
    php82-fpm \
    php82-gd \
    php82-gettext \
    php82-opcache \
    php82-pcntl \
    php82-zip \
    php82-pgsql \
    php82-redis \
    php82-xdebug \
    php82-sockets

# Install extensions for PHP
RUN docker-php-ext-install \
    zip \
    bcmath \
    pdo \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    gd \
    sockets

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN adduser -G www-data -u $uid -h /home/$user -s /bin/ash $user -D
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:www-data /home/$user

# Workdir and Copy all files
WORKDIR /var/www/html
COPY . ./

# Change owner of html folder
RUN chown -R $user:www-data ./

# Chenge to user
USER $user

# Running composer and optimizing autoloader and prepare laravel enviroment
RUN cp .env.example .env
RUN composer update --optimize-autoloader --with-all-dependencies
RUN chmod -R 775 bootstrap/cache storage/

# Otimizacao
RUN php artisan key:generate

# Expose port - close in production
EXPOSE 8000

# Run command of app
CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000" ]
