FROM celsonery/php-laravel-mysql:latest as build
WORKDIR /usr/local/bin/app
COPY . ./
RUN composer update -o --no-dev --with-all-dependencies

FROM celsonery/php-laravel-mysql:latest as production
WORKDIR /usr/local/bin/app
COPY --from=build /usr/local/bin/app ./
RUN chmod -R 777 storage
RUN chmod -R 777 bootstrap/cache
RUN php artisan storage:link
EXPOSE 8000
CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000" ]
