name: Pit-Api Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Pit-Api Tests
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3.9'
    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --optimize-autoloader -q --no-ansi --no-interaction --no-scripts --no-progress

    - name: Create Database
      run: touch database/database.sqlite

    - name: Generate key
      run: |
        php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      run: php artisan migrate

    - name: Optimize application
      run: php artisan optimize:clear

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

    - name: Execute qualit tests with Pint
      run: ./vendor/bin/pint -v --test
